<map version="0.9.0"><node text="files"><node text="animals.txt"><node text="pets"/>
<node text="pet animals"/>
<node text="pet dogs"/>
<node text="pet deer"/>
<node text="white mouse"/>
<node text="mewing sound"/>
<node text="different tricks"/>
<node text="daylong work"/>
<node text="many stories"/>
<node text="monotonous profession"/>
<node text="most people"/>
<node text="peculiar habits"/>
<node text="european friend"/>
<node text="food grains"/>
<node text="many angles"/>
<node text="innocent friends"/>
<node text="innocent pets"/>
<node text="people"/>
<node text="animals"/>
<node text="cat"/>
<node text="attractive features"/>
<node text="cruel masters"/>
<node text="faithful animal"/>
<node text="chief intention"/>
<node text="same bed"/>
<node text="remote today"/>
<node text="peace"/>
<node text="dog"/>
<node text="rats"/>
<node text="birds"/>
<node text="master"/>
<node text="monkeys"/>
<node text="role"/>
<node text="few religious words"/>
<node text="life"/>
<node text="friends"/>
<node text="names"/>
<node text="funny names"/>
<node text="old days"/>
<node text="courageous acts"/>
</node><node text="cars.txt"><node text="careful person"/>
<node text="many drives"/>
<node text="bit late"/>
<node text="bus"/>
<node text="sister"/>
<node text="previous night"/>
<node text="school"/>
<node text="indelible imprint"/>
<node text="careful driver"/>
<node text="car hurriedly"/>
<node text="car full"/>
<node text="traffic police car"/>
<node text="severe injuries"/>
<node text="children"/>
<node text="accidents"/>
<node text="school bus"/>
<node text="left turning"/>
<node text="driver"/>
<node text="congested road"/>
<node text="slippery road"/>
<node text="minor cuts"/>
<node text="car"/>
<node text="tragic accident"/>
<node text="accident spot"/>
<node text="few adults"/>
<node text="injured school children"/>
<node text="few cars"/>
<node text="school children"/>
<node text="road"/>
<node text="left hand"/>
<node text="statements"/>
<node text="meantime passers-by"/>
<node text="head"/>
<node text="innocent lives"/>
<node text="steering wheel"/>
<node text="mind"/>
<node text="cold morning"/>
</node><node text="file3.txt"><node text="neighboring countries"/>
<node text="many countries"/>
<node text="diverse regional languages"/>
<node text="other language"/>
<node text="language english"/>
<node text="own language"/>
<node text="global language"/>
<node text="country"/>
<node text="outsourcing business"/>
<node text="language"/>
<node text="b p o’s"/>
<node text="globalized world"/>
<node text="education"/>
<node text="india"/>
<node text="english today"/>
<node text="global nature"/>
<node text="good stead"/>
<node text="government jobs"/>
<node text="good placement"/>
<node text="literature available"/>
<node text="finest literature"/>
<node text="foreign universities"/>
<node text="ruskin bond"/>
<node text="class"/>
<node text="india’s economy boom"/>
<node text="english"/>
<node text="own mother tongue"/>
<node text="middle class youth"/>
<node text="english language"/>
<node text="al kannada"/>
<node text="higher education"/>
<node text="world"/>
<node text="technical education such"/>
<node text="proficiency"/>
<node text="lingua franca"/>
<node text="knowledge"/>
<node text="today"/>
<node text="indians"/>
<node text="private sector"/>
</node><node text="folder2"><node text="folder2.1"><node text="file2.1.2.txt"><node text="simple empty document"/>
<node text="lekha"/>
</node></node></node><node text="folder1"><node text="hello.txt"></node></node><node text="english.txt"><node text="neighboring countries"/>
<node text="many countries"/>
<node text="diverse regional languages"/>
<node text="other language"/>
<node text="language english"/>
<node text="own language"/>
<node text="global language"/>
<node text="country"/>
<node text="outsourcing business"/>
<node text="language"/>
<node text="b p o’s"/>
<node text="globalized world"/>
<node text="education"/>
<node text="india"/>
<node text="english today"/>
<node text="global nature"/>
<node text="good stead"/>
<node text="government jobs"/>
<node text="good placement"/>
<node text="literature available"/>
<node text="finest literature"/>
<node text="foreign universities"/>
<node text="ruskin bond"/>
<node text="class"/>
<node text="india’s economy boom"/>
<node text="english"/>
<node text="own mother tongue"/>
<node text="middle class youth"/>
<node text="english language"/>
<node text="al kannada"/>
<node text="higher education"/>
<node text="world"/>
<node text="technical education such"/>
<node text="proficiency"/>
<node text="lingua franca"/>
<node text="knowledge"/>
<node text="today"/>
<node text="indians"/>
<node text="private sector"/>
</node></node></map>